config:
  required_keys:
    - "bot.name"
    - "bot.token"
    - "bot.prefix"
    - "database.host"
    - "database.db_name"
    - "database.user_name"
    - "database.password"

bot:
  name: "Nya-chan"
  description: "A Geeky bot"
  token: !ENV "TOKEN"

  prefix: "!n."
  cogs:
    - core

  debug: !ENV "DEBUG"

database:
  host: "127.0.0.1"
  port: 3306
  db_name: "bot_db"

  user_name: "bot"
  password: "password"