# Bot config
config:
  required_keys:
    - "bot.name"
    - "bot.token"
    - "bot.prefix"
    - "database.host"
    - "database.database"
    - "database.user.name"
    - "database.user.password"

  debug: !ENV "DEBUG"

  # What to log
  logs:
    chat: yes
    guild_entry: yes

    commands:
      execute: yes
      error: yes
      complete: yes

# Internal bot config
bot:
  # Bot name
  name: "Nya-chan"

  # Bot description
  description: "A Geeky bot"

  # Bot token
  token: !ENV "TOKEN"

  # Bot prefix
  prefix: "!n."

  # Bot cogs to load on start
  cogs: []

# Database config (ArangoDB)
database:
  # Host address
  host: "127.0.0.1"

  # Host port
  port: 8529

  # Database name
  database: "bot_db"

  # Database user information
  user:
    name: "bot"
    password: "password"
