config:
  required_keys:
    - "bot.name"
    - "bot.token"
    - "bot.prefix"
    - "database.host"
    - "database.database"
    - "database.user.name"
    - "database.user.password"

  debug: !ENV "DEBUG"

  logs:
    chat: yes

    commands:
      execute: yes
      error: yes
      complete: yes

bot:
  name: "Nya-chan"
  description: "A Geeky bot"
  token: !ENV "TOKEN"

  prefix: "!n."
  cogs: []

database:
  host: "127.0.0.1"
  port: 3306
  database: "bot_db"

  user:
    name: "bot"
    password: "password"